apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  DATABASE_NAME: U3RvcmU=
  DATABASE_USER: cG9zdGdyZXM=
  DATABASE_PASSWORD: QWRtaW4=
  SECRET_KEY: PWpxaXk9enlfc2F2JikpOHF4aCRfZGsraXBoMF56eS1eQEBpbGdzLWg0JHJ6ZTgmIzU=

