name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Decode and set environment variables
        run: |
          echo "AT_USERNAME=$(echo '${{ secrets.AT_USERNAME }}' | base64 -d)" >> $GITHUB_ENV
          echo "AT_SHORT_CODE=$(echo '${{ secrets.AT_SHORT_CODE }}' | base64 -d)" >> $GITHUB_ENV
          echo "AT_API_KEY=$(echo '${{ secrets.AT_API_KEY }}' | base64 -d)" >> $GITHUB_ENV

      - name: Run Tests
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          source venv/bin/activate
          # Debug: Check if variables are set (without exposing values)
          echo "Checking database configuration..."
          [ -z "$DB_NAME" ] && echo "DB_NAME is not set" || echo "DB_NAME is set"
          [ -z "$DB_USER" ] && echo "DB_USER is not set" || echo "DB_USER is set"
          [ -z "$DB_HOST" ] && echo "DB_HOST is not set" || echo "DB_HOST is set"
          [ -z "$DB_PORT" ] && echo "DB_PORT is not set" || echo "DB_PORT is set"
          pytest -v   

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/e-commerce-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerce-service:latest

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Validate KUBECONFIG Secret
        run: |
          if [ -z "${{ secrets.KUBECONFIG }}" ]; then
            echo "Error: KUBECONFIG secret is missing!"
            exit 1
          fi  

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          echo "KUBECONFIG=$(pwd)/kubeconfig.yaml" >> $GITHUB_ENV

      - name: Deploy Postgres to Kubernetes
        run: |
          kubectl apply -f k8s/postgres.yaml
          kubectl rollout status statefulset/postgres --timeout=120s

      - name: Deploy Application to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl set image deployment/ecommerce-app ecommerce-app=${{ secrets.DOCKER_USERNAME }}/e-commerce-service:latest
          kubectl rollout status deployment/ecommerce-app --timeout=120s
